# Generated by Django 3.2 on 2022-11-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_model', '0002_alter_book_price_alter_discount_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='book',
            field=models.ManyToManyField(blank=True, to='custom_model.Book'),
        ),
    ]
